name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, staging]
  pull_request:
    branches: [master, staging]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
        # mongodb-version: [4.0]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        # - name: Start MongoDB
        #   uses: supercharge/mongodb-github-action@1.3.0
        #   with:
        #     mongodb-version: ${{ matrix.mongodb-version }}
      - name: npm install, build, and test
        env:
          CI: true
        run: |
          yarn install
          yarn test
      # - uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repositories
      #     fail_ci_if_error: true # optional (default = false)
